import { Router, type Request, type Response } from "express";

const router = Router();

function extractCodeBlocks(content: string): Array<{ language: string; filename: string; code: string }> {
  const blocks: Array<{ language: string; filename: string; code: string }> = [];
  const regex = /```(\w+)?\n([\s\S]*?)```/g;
  let match;
  let counter = 0;

  while ((match = regex.exec(content)) !== null) {
    counter++;
    const lang = match[1] ?? "txt";
    const code = match[2] ?? "";

    const extMap: Record<string, string> = {
      typescript: "ts", javascript: "js", python: "py", html: "html",
      css: "css", json: "json", yaml: "yaml", yml: "yml", sql: "sql",
      bash: "sh", shell: "sh", go: "go", rust: "rs", java: "java",
      cpp: "cpp", c: "c", ruby: "rb", php: "php", swift: "swift",
      kotlin: "kt", markdown: "md", txt: "txt",
    };

    const ext = extMap[lang] ?? lang ?? "txt";
    const filename = `file_${counter}.${ext}`;
    blocks.push({ language: lang, filename, code });
  }

  return blocks;
}

function buildZipBuffer(files: Array<{ name: string; content: string }>): Buffer {
  const parts: Buffer[] = [];

  const localHeaders: Buffer[] = [];
  const centralDirs: Buffer[] = [];
  let offset = 0;

  for (const file of files) {
    const nameBuffer = Buffer.from(file.name, "utf8");
    const dataBuffer = Buffer.from(file.content, "utf8");

    const localHeader = Buffer.alloc(30 + nameBuffer.length);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(0, 6);
    localHeader.writeUInt16LE(0, 8);
    localHeader.writeUInt16LE(0, 10);
    localHeader.writeUInt16LE(0, 12);
    localHeader.writeUInt32LE(0, 14);
    localHeader.writeUInt32LE(dataBuffer.length, 18);
    localHeader.writeUInt32LE(dataBuffer.length, 22);
    localHeader.writeUInt16LE(nameBuffer.length, 26);
    localHeader.writeUInt16LE(0, 28);
    nameBuffer.copy(localHeader, 30);

    localHeaders.push(localHeader);
    parts.push(localHeader, dataBuffer);

    const centralDir = Buffer.alloc(46 + nameBuffer.length);
    centralDir.writeUInt32LE(0x02014b50, 0);
    centralDir.writeUInt16LE(20, 4);
    centralDir.writeUInt16LE(20, 6);
    centralDir.writeUInt16LE(0, 8);
    centralDir.writeUInt16LE(0, 10);
    centralDir.writeUInt16LE(0, 12);
    centralDir.writeUInt16LE(0, 14);
    centralDir.writeUInt32LE(0, 16);
    centralDir.writeUInt32LE(dataBuffer.length, 20);
    centralDir.writeUInt32LE(dataBuffer.length, 24);
    centralDir.writeUInt16LE(nameBuffer.length, 28);
    centralDir.writeUInt16LE(0, 30);
    centralDir.writeUInt16LE(0, 32);
    centralDir.writeUInt16LE(0, 34);
    centralDir.writeUInt16LE(0, 36);
    centralDir.writeUInt32LE(0x81a40000, 38);
    centralDir.writeUInt32LE(offset, 42);
    nameBuffer.copy(centralDir, 46);

    centralDirs.push(centralDir);
    offset += localHeader.length + dataBuffer.length;
  }

  const centralDirBuffer = Buffer.concat(centralDirs);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(0, 4);
  eocd.writeUInt16LE(0, 6);
  eocd.writeUInt16LE(files.length, 8);
  eocd.writeUInt16LE(files.length, 10);
  eocd.writeUInt32LE(centralDirBuffer.length, 12);
  eocd.writeUInt32LE(offset, 16);
  eocd.writeUInt16LE(0, 20);

  return Buffer.concat([...parts, centralDirBuffer, eocd]);
}

router.post("/download/zip", async (req: Request, res: Response): Promise<void> => {
  const { content, projectName = "thinker-output" } = req.body as {
    content?: string;
    projectName?: string;
  };

  if (!content) {
    res.status(400).json({ error: "content is required" });
    return;
  }

  const codeBlocks = extractCodeBlocks(content);

  const files: Array<{ name: string; content: string }> =
    codeBlocks.length > 0
      ? codeBlocks.map((b) => ({ name: b.filename, content: b.code }))
      : [{ name: "output.md", content }];

  const readme = [
    `# ${projectName}`,
    "",
    `Generated by Thinker AI — ${new Date().toISOString().split("T")[0]}`,
    "",
    "## Files",
    ...files.map((f) => `- ${f.name}`),
    "",
    "---",
    "Build complete. Reviewed by multiple agents.",
  ].join("\n");

  files.unshift({ name: "README.md", content: readme });

  const zipBuffer = buildZipBuffer(files);
  const safeName = projectName.replace(/[^a-z0-9-_]/gi, "-").toLowerCase();

  res.setHeader("Content-Type", "application/zip");
  res.setHeader("Content-Disposition", `attachment; filename="${safeName}.zip"`);
  res.setHeader("Content-Length", zipBuffer.length);
  res.send(zipBuffer);
});

export default router;
