kind = "mobile"
previewPath = "/"
title = "Thinker AI"
version = "1.0.0"
id = "artifacts/mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 8081

[services.development]
run = "pnpm --filter @workspace/mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mobile", "run", "serve" ]

[services.env]
PORT = "8081"
BASE_PATH = "/"
